fix(ll:Layers): merge layer params specifiques...
IGNF/geoportal-extensions pull request #319
Opened 2022-01-27 15:34 UTC by elias75015

...et non natifs

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [ ] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [ ] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

le paramètre format renseigné par l'utilisateur n'est pas pris en compte pour les couches WMTS

## Quel est le nouveau comportement :

Le paramètre format (et les autres paramètres spécifiques sont pris en compte lors de l'ajout d'une couche WMTS.

L'exemple suivant est censé fonctionner : 
```javascript
function go() {
    var map = L.map('map', {
        crs: L.geoportalCRS.EPSG2154,
    }).setView([45.7481787494123, 4.725191295146942], 18);
    var lyr = L.geoportalLayer.WMTS({
        layer: "CADASTRALPARCELS.PARCELS.L93"
    },
    {
    	format:"image/png"
    });
    lyr.addTo(map); // ou map.addLayer(lyr);
}

Gp.Services.getConfig({
    apiKey: "lambert93",
    onSuccess: go
});
```

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [ ] Non

## Autres informations

2022-02-03 09:03 UTC, lowzonenose requested changes
J'ai l'impression que les param natif de Leaflet ne peuvent plus être passé dans le constructeur...

2022-02-03 09:03 UTC, lowzonenose commented on DRAFT_CHANGELOG.md
> +    - hot fix sur le drag&drop cassé sur Chrome v 97 (138aecced48a3f91503b6d3ec33e917d4cb16e04)
sur le widget 'LayerSwitcher'

2022-02-03 09:03 UTC, lowzonenose commented on src/Leaflet/Layers/Layers.js
> +        L.Util.extend(paramsWms, this.settings);
hummm..., peut on toujours passer les paramètres natifs de Leaflet tel que l'opacité ?

2022-02-03 15:06 UTC, elias75015 commented on src/Leaflet/Layers/Layers.js
> +        L.Util.extend(paramsWms, this.settings);
Effectivement, je ne sais pas si j'ai résolu de la manière la plus propre, mais désormais c'est OK :
- les paramètres utilisateur surchargent également les paramètres natifs Leaflet (paramsNative)
- les paramètres utilisateur surchargent les paramètres par défaut du service (paramsWms/Wmts)

Pb (sans impact a priori) : on se retrouve avec des paramètres en doublon dans ces deux objets.

2022-02-07 15:51 UTC, lowzonenose approved these changes

2022-02-07 16:08 UTC, merged