fix: faute de frappe corrigée pour faire fonctionner GP avec Leaflet et Angular
IGNF/geoportal-extensions pull request #382
Opened 2024-07-25 17:14 UTC by RupertBarrow

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [X] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [ ] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [X] Les tests (`npm run test`) sont passés localement

De plus, l'application `github:geoportal-third-party-integration-master/simple-map-leaflet-angular`qui ne buildait pas build correctement maintenant.

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [X] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [ ] Autres (décrire ci-après) : 

## Quel est le comportement actuel (avant PR) :

geoportal-extensions-leaflet n'est pasz utilisable dans un context Leaflet + Angular, car le fichier Styles.js importe des CSS. C'est à cause de la faute de frappe décrite dans ISSUE #381 qui est corrigée par cette PR.

Numéro du ticket : #381

## Quel est le nouveau comportement :

- correction de la faute de frappe
- le build génère donc un Styles.js qui est compatible avec Leaflet et Angular
- le build de `github:geoportal-third-party-integration-master/simple-map-leaflet-angular` ne fonctionnait pas : c'est maintenant corrigé

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [X] Non

## Autres informations

2024-07-26 12:23 UTC, azarz approved these changes

2024-07-29 10:51 UTC, elias75015 requested changes
Bonjour,

merci pour votre PR. 

Quelques changements pour que celle-ci fonctionne aussi en mode package npm. En effet, aucune release npm n'a été publiée pour le package replace-bundle-webpack-plugin.

https://github.com/IGNF/geoportal-extensions/blob/77c1c97672d48031f20e9b3b8ed148c9a525e9f6/package.json#L123

Remplacé par le fork corrigé de l'erreur de typo :
"replace-bundle-webpack-plugin-edited": "^1.0.0",

https://github.com/IGNF/geoportal-extensions/blob/77c1c97672d48031f20e9b3b8ed148c9a525e9f6/build/webpack/webpack.config.itowns.js#L16

https://github.com/IGNF/geoportal-extensions/blob/77c1c97672d48031f20e9b3b8ed148c9a525e9f6/build/webpack/webpack.config.leaflet.js#L16

https://github.com/IGNF/geoportal-extensions/blob/77c1c97672d48031f20e9b3b8ed148c9a525e9f6/build/webpack/webpack.config.openlayers.js#L16

https://github.com/IGNF/geoportal-extensions/blob/77c1c97672d48031f20e9b3b8ed148c9a525e9f6/build/webpack/webpack.config.openlayers.modules.js#L16C1-L16C69

Remplacer par le package var ReplaceWebpackPlugin = require("replace-bundle-webpack-plugin-edited");

2024-07-30 11:54 UTC, lowzonenose reviewed
On peut aussi héberger en local le plugin comme pour les plugins **JsDocWebPackPlugin**  et **HandlebarsPlugin** (cf. ./build/scripts/webpackPlugins) afin d'éviter d'utiliser un fork. On aurait ainsi la maintenance.

2024-08-08 16:25 UTC, elias75015 approved these changes
OK pour moi, merci

2024-08-08 16:26 UTC, merged